version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_USER_ID: $APP_USER_ID
        APP_GROUP_ID: $APP_GROUP_ID
    restart: always
    expose:
      - $APP_PORT
    ports:
      - $APP_PORT:$APP_PORT
    env_file:
      - ./.env
    depends_on:
      - cache

  cache:
    image: "memcached:alpine"
    restart: on-failure
    env_file:
      - ./.env
    expose:
      - $MEMCACHED_PORT
