name: Code QA

on: [push]

permissions:
  contents: read

jobs:
  code-qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black pytest httpx trio
        pip install -r requirements.txt
    - name: Formatting the code with black
      run: |
        black $(git ls-files '*.py')
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under 9.0 $(git ls-files '*.py')
